### PR TITLE
Fix uploading large files

### PR DESCRIPTION
**Pull request by exchgr**
# Why

Large files fail to upload from strapi to cloudflare images because they exceeded `maxBodyLength`:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
```

# How
- update axios to latest `^1.4.0`
- use newer axios' detection of `multipart/form-data` to facilitate uploading large files
- remove dependencies on `form-data` and `stream`
- implement strapi plugins' `uploadStream` callback

### CODE REVIEW

**Comment by 0xsven** [comment]
@sanjay-io any chance we could get this merged? :)

**Comment by sanjayiothakur** [comment]
ah, yes, thanks for the nudge @0xsven, will review and cut off a release later today.

**Comment by sanjayiothakur** [comment]
@exchgr @0xsven should see the changes in version 4.2.0, sorry for the delay by a day!

**Comment by exchgr** [comment]
woo, thank you very much!

**Pull request merged**
